homepage: https://openwrt.org/docs/techref/relayd
language: c
primary_contact: steven@midlink.org
auto_ccs:
  - dedeckeh@gmail.com
main_repo: https://github.com/Dudcom/relayd-oss-fuzz.git
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
  - i386 
